In [4]:
import pandas as pd
import openpyxl


table = pd.read_excel('WT_Grid_Traditional.xlsx', skiprows = 0)
table.fillna(value = '0', method = None)

,Scorer,Date,Article Headline,Outlet/Publication,Post Type,Engagement,Reach,Trash,Press Release,Stocks,...,Trump/Administration Changes,Blockchain/ Technology,Brexit,TBD,Aubrey McClendon,Election Coverage,matched_profile,title,content,url
0,CM,2017-01-27,National Housing Equity Investor Renews 18K-SF...,http://commercialobserver.com/,OTHER,2,80000,0,0,0,...,0,0,0,0,0,0,"SEARCH / / Bessemer Trust,PANEL / Tier 1 - UP...",National Housing Equity Investor Renews 18K-SF...,...and is known as the International Building ...,https://commercialobserver.com/2017/01/nationa...
1,CM,2017-01-18,Patterson: This is going to be the year with a...,http://yahoo.com/,OTHER,0,0,0,0,0,...,1,0,0,0,0,0,"SEARCH / / Bessemer Trust,PANEL / Tier 1 - UP...",Patterson: This is going to be the year with a...,"Rebecca Patterson, Bessemer Trust managing dir...",https://hk.finance.yahoo.com/video/patterson-g...
2,CM,2017-01-17,Patterson: This is going to be the year with a...,http://cnbc.com/,OTHER,128,1272195,0,0,0,...,1,0,0,0,0,0,"SEARCH / / Bessemer Trust,PANEL / Tier 1 - UP...",Patterson: This is going to be the year with a...,...be the year with a lot of push and pull\n\n...,http://video.cnbc.com/gallery/?video=3000585316
3,CM,2017-01-18,Patterson: This is going to be the year with a...,http://nasdaq.com/,OTHER,0,5585366,0,0,0,...,1,0,0,0,0,0,"SEARCH / / Bessemer Trust,PANEL / Tier 2 - UP...",Patterson: This is going to be the year with a...,"Rebecca Patterson, Bessemer Trust managing dir...",http://www.nasdaq.com/video/587fb34b1c689973d4...
4,JC,2017-01-25,‘Great rotation’ highlights clash over unseen ...,http://risk.net/,MAGAZINE,179,95652,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",‘Great rotation’ highlights clash over unseen ...,"...Northern Trust Asset Management in Chicago,...",http://www.risk.net/risk/feature/2480714/-grea...
5,RS,2017-01-09,Aries Capital merges mortgage banking business...,http://chicagobusiness.com/,MAGAZINE,227,679012,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Aries Capital merges mortgage banking business...,...al property financing businesses in the cou...,http://www.chicagobusiness.com/realestate/2017...
6,CM,2017-01-10,Politics and earnings are the biggest risks to...,http://yahoo.com/,OTHER,0,0,0,0,0,...,1,0,0,0,0,0,"SEARCH / / Bessemer Trust,PANEL / Tier 1 - UP...",Politics and earnings are the biggest risks to...,"Chris Cordaro, RegentAtlantic Capital, and Reb...",https://hk.finance.yahoo.com/video/politics-ea...
7,RS,2017-01-20,"January 20, 2017 Legal notices - Orlando Busin...",http://bizjournals.com/,MAGAZINE,1,8698979,1,0,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...","January 20, 2017 Legal notices - Orlando Busin...","...and Investor Trustee\n\nServices, Llcas Tru...",http://www.bizjournals.com/orlando/resources/l...
8,RS,2017-01-20,"January 20, 2017 Legal notices - Orlando Busin...",http://bizjournals.com/,MAGAZINE,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...","January 20, 2017 Legal notices - Orlando Busin...","...and Investor Trustee\n\nServices, Llcas Tru...",http://assets-origin.bizjournals.com/orlando/r...
9,JC,2017-01-10,《美国上市公司业绩公布日程表》--1月11日至1月18日,http://reuters.com/,AGENCY,0,177254,0,0,1,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月11日至1月18日,Bancorp) 1月18日 BMO SCHW.N Q4 2016 嘉信理财(Charles...,http://cn.reuters.com/article/idCNL4S1F11JC
10,JC,2017-01-11,《美国上市公司业绩公布日程表》--1月12日至1月19日,http://reuters.com/,AGENCY,0,177254,0,0,1,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月12日至1月19日,...Schwab) 1月18日 BMO NTRS.OQ Q4 2016 Northern ...,http://cn.reuters.com/article/idCNL4S1F21WS?fe...
11,JC,2017-01-12,《美国上市公司业绩公布日程表》--1月13日至1月20日,http://reuters.com/,AGENCY,0,177254,0,0,1,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月13日至1月20日,...Schwab) 1月18日 BMO NTRS.OQ Q4 2016 Northern ...,http://cn.reuters.com/article/idCNL4S1F31XI
12,JC,2017-01-15,《美国上市公司业绩公布日程表》--1月16日至1月23日,http://reuters.com/,AGENCY,0,177254,0,0,1,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月16日至1月23日,...2017-01-18 BMO NTRS.OQ Q4 2016 Northern Tru...,http://cn.reuters.com/article/idCNL4S1F61PN
13,JC,2017-01-16,《美国上市公司业绩公布日程表》--1月17日至1月24日,http://reuters.com/,AGENCY,0,177254,0,0,1,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月17日至1月24日,...2017-01-18 BMO NTRS.OQ Q4 2016 Northern Tru...,http://cn.reuters.com/article/idCNL4S1F71IY
14,JC,2017-01-17,《美国上市公司业绩公布日程表》--1月18日至1月25日,http://reuters.com/,AGENCY,0,177254,0,0,1,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月18日至1月25日,...2017-01-18 BMO NTRS.OQ Q4 2016 Northern Tru...,http://cn.reuters.com/article/idCNL4S1F81LA
15,JC,2017-01-31,3 Stocks To Sell If Trump Names Japan A Curren...,http://barrons.com/,BLOG,5,556086,0,0,0,...,1,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",3 Stocks To Sell If Trump Names Japan A Curren...,\n\nWorrying that Trump may shift his harsh cu...,http://blogs.barrons.com/asiastocks/2017/01/31...
16,JC,2017-01-10,A batalha das montadoras para sobreviver na er...,http://wsj.com/,NEWSPAPER,4,36318,0,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",A batalha das montadoras para sobreviver na er...,...não parecem ser candidatos óbvios. Neil Cam...,http://br.wsj.com/articles/SB12742076995748244...
17,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://ap.org/,AGENCY,0,3462874,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://hosted.ap.org/dynamic/stories/F/FINANCI...
18,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://ap.org/,AGENCY,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://akamai.hosted.ap.org/dynamic/stories/F/...
19,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://yahoo.com/,OTHER,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",https://nz.finance.yahoo.com/news/adobe-coluci...
20,JC,2017-01-18,Adobe and CoLucid Pharma Edge Higher While Tar...,http://nytimes.com/,NEWSPAPER,0,130259256,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma Edge Higher While Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.nytimes.com/aponline/2017/01/18/bus...
21,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://bradenton.com/,NEWSPAPER,0,224299,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.bradenton.com/news/business/article...
22,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://equities.com/,OTHER,0,196969,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million ....",https://www.equities.com/news/adobe-and-coluci...
23,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://kansascity.com/,NEWSPAPER,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://qa1.kansascity.com/news/business/nation...
24,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://yahoo.com/,OTHER,0,32606720,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://finance.yahoo.com/news/adobe-colucid-ph...
25,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://salon.com/,MAGAZINE,0,10341176,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.salon.com/2017/01/18/adobe-and-colu...
26,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://kansascity.com/,NEWSPAPER,0,1628205,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.kansascity.com/news/business/nation...
27,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://ap.org/,AGENCY,0,3221557,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://bigstory.ap.org/article/e5da639891be4ff...
28,JC,2017-01-17,Adobe and CoLucid Pharma edge higher while Tar...,http://startribune.com/,NEWSPAPER,0,4757009,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.startribune.com/adobe-and-colucid-p...
29,JC,2017-01-16,AFTAs 2016 ─ All the Winners and Why They Won,http://waterstechnology.com/,OTHER,18,41176,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",AFTAs 2016 ─ All the Winners and Why They Won,"...executive, sell side); Scott Murray (Northe...",http://www.waterstechnology.com/waters/news/24...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,RV,2017-03-30,SunTrust taps Jenna Kelly to lead Atlanta Divi...,http://bizjournals.com/,MAGAZINE,26,7383721,1,0,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",SunTrust taps Jenna Kelly to lead Atlanta Divi...,"...to Financial Well-Being ' for our clients,""...",http://www.bizjournals.com/atlanta/news/2017/0...
823,RV,2017-03-21,SunTrust: Small and Mid-market Business Bullis...,http://benzinga.com/,BLOG,0,1140000,0,1,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 1 - UPDATED ...",SunTrust: Small and Mid-market Business Bullis...,"...credit, trust, investment, mortgage, asset ...",https://www.benzinga.com/pressreleases/17/03/n...
824,RV,2017-03-21,SunTrust: Small and Mid-market Business Bullis...,http://itbusinessnet.com/,OTHER,0,909,0,1,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",SunTrust: Small and Mid-market Business Bullis...,"...deposit, credit, trust, investment, mortgag...",http://business.itbusinessnet.com/article/SunT...
825,RV,2017-03-21,SunTrust: Small and Mid-market Business Bullis...,http://itbusinessnet.com/,OTHER,0,118181,0,1,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",SunTrust: Small and Mid-market Business Bullis...,"...deposit, credit, trust, investment, mortgag...",http://www.itbusinessnet.com/articles/viewarti...
826,RV,2017-03-21,SunTrust: Small and Mid-market Business Bullis...,http://itbusinessnet.com/,OTHER,0,2727,0,1,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",SunTrust: Small and Mid-market Business Bullis...,"...deposit, credit, trust, investment, mortgag...",http://security.itbusinessnet.com/article/SunT...
827,RV,2017-03-20,TechIBM Launches New Cloud Service for Buildin...,http://fortune.com/,BLOG,0,13809524,0,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",TechIBM Launches New Cloud Service for Buildin...,"...including Northern Trust, [f500link]Wal-Mar...",http://fortune.com/go/tech/ibm-blockchain-serv...
828,AG,2017-03-31,Turkish Construction Giant Hit with $237M Unpa...,http://law360.com/,OTHER,0,1023809,1,0,0,...,0,0,0,0,0,0,"SEARCH / Client / Wilmington Trust,PANEL / Tie...",Turkish Construction Giant Hit with $237M Unpa...,"Law360, London (March 31, 2017, 5:28 PM BST) -...",http://www.law360.com/
829,RV,2017-03-24,UPDATE 1-Carlyle extends private equity oil ru...,http://reuters.com/,AGENCY,0,44879228,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",UPDATE 1-Carlyle extends private equity oil ru...,...\nFunds News\n\nCORRECTED-Fed gives Norther...,http://www.reuters.com/article/shell-carlyle-g...
830,RV,2017-03-24,UPDATE 1-Fed gives four foreign banks 'living ...,http://reuters.com/,AGENCY,0,44879228,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,SEARCH / / SunTrus...",UPDATE 1-Fed gives four foreign banks 'living ...,"...One Financial Corp, Comerica Inc, Discover ...",http://www.reuters.com/article/usa-fed-livingw...
831,RV,2017-03-24,UPDATE 1-Fed gives four foreign banks 'living ...,http://investing.com/,OTHER,0,1194035,0,1,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",UPDATE 1-Fed gives four foreign banks 'living ...,"...'living will' extension, faults Northern Tr...",https://in.investing.com/news/stock-market-new...
832,RV,2017-03-24,UPDATE 1-Fed gives four foreign banks 'living ...,http://businessinsider.com/,OTHER,0,465189,1,0,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 1 - UPDATED ...",UPDATE 1-Fed gives four foreign banks 'living ...,"...Ally Financial Inc, BB&T Corp, Capital One ...",http://markets.businessinsider.com/news/stocks...
833,RV,2017-03-24,UPDATE 1-N.Y. Fed raises U.S. Q1 GDP estimate ...,http://reuters.com/,AGENCY,0,44879228,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",UPDATE 1-N.Y. Fed raises U.S. Q1 GDP estimate ...,"...four foreign banks 'living will' extension,...",http://www.reuters.com/article/usa-economy-nyf...
834,RV,2017-03-22,"Walter Investment Management (NYSE: WAC), Cent...",http://bizjournals.com/,MAGAZINE,20,7383721,1,0,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...","Walter Investment Management (NYSE: WAC), Cent...","...Ablin , chief investment officer at BMO Pri...",http://www.bizjournals.com/tampabay/news/2017/...
835,RV,2017-03-22,"Walter Investment Management (NYSE: WAC), Cent...",http://bizjournals.com/,MAGAZINE,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...","Walter Investment Management (NYSE: WAC), Cent...","...Ablin , chief investment officer at BMO Pri...",http://assets-origin.bizjournals.com/tampabay/...
836,RV,2017-03-21,Waning Confidence in Trump Trade Drags on Stoc...,http://etftrends.com/,OTHER,6,76470,0,0,0,...,1,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Waning Confidence in Trump Trade Drags on Stoc...,"...forefront of investors’ minds,” Katie Nixon...",http://www.etftrends.com/2017/03/waning-confid...
837,RV,2017-03-18,Welcome to the WSO Company Database. | Wall St...,http://wallstreetoasis.com/,OTHER,15,930000,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Welcome to the WSO Company Database. | Wall St...,...independent financial investment firm that ...,https://www.wallstreetoasis.com/wso-company-da...
838,RV,2017-03-28,Wells Fargo (NYSE: WFC) agrees to $110 million...,http://bizjournals.com/,MAGAZINE,0,7383721,1,0,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",Wells Fargo (NYSE: WFC) agrees to $110 million...,"1, 2009 to the settlement date.\n\nThe court m...",http://www.bizjournals.com/orlando/news/2017/0...
839,RV,2017-03-28,Wells Fargo (NYSE: WFC) agrees to $110 million...,http://bizjournals.com/,MAGAZINE,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",Wells Fargo (NYSE: WFC) agrees to $110 million...,"1, 2009 to the settlement date.\n\nThe court m...",http://assets-origin.bizjournals.com/orlando/n...
840,RV,2017-03-20,What Is Blockchain? IBM Launches Service For E...,http://ibtimes.com/,MAGAZINE,170,16299213,0,0,0,...,0,1,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",What Is Blockchain? IBM Launches Service For E...,...provider SecureKey; financial services comp...,http://www.ibtimes.com/what-blockchain-ibm-lau...
841,RV,2017-03-24,What’s next for infill around the Valley?,http://bizjournals.com/,MAGAZINE,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",What’s next for infill around the Valley?,"...\nAlready taking space: State Farm, Norther...",http://assets-origin.bizjournals.com/phoenix/n...
842,RV,2017-03-24,What’s next for infill around the Valley?,http://bizjournals.com/,MAGAZINE,13,7383721,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",What’s next for infill around the Valley?,"...\nAlready taking space: State Farm, Norther...",http://www.bizjournals.com/phoenix/news/2017/0...
843,AG,2017-03-24,Wilmington Trust to oversee $2.7B Volkswagen t...,http://delawareonline.com/,OTHER,0,0,0,0,0,...,0,0,0,0,0,0,"SEARCH / Client / Wilmington Trust,PANEL / Tie...",Wilmington Trust to oversee $2.7B Volkswagen t...,Wilmington Trust will serve as the trustee of ...,http://ux.delawareonline.com/
844,AG,2017-03-24,Wilmington Trust to oversee $2.7B Volkswagen t...,http://delawareonline.com/,OTHER,1,500000,0,0,0,...,0,0,0,0,0,0,"SEARCH / Client / Wilmington Trust,PANEL / Tie...",Wilmington Trust to oversee $2.7B Volkswagen t...,Wilmington Trust will serve as the trustee of ...,http://www.delawareonline.com/
845,AG,2017-03-20,Wilmington Trust will act as trustee in $2.7 b...,http://delawarebusinesstimes.com/,BLOG,24,4761,0,0,0,...,0,0,0,0,0,0,"SEARCH / Client / Wilmington Trust,PANEL / Tie...",Wilmington Trust will act as trustee in $2.7 b...,"WILMINGTON – Wilmington Trust, one of the larg...",http://www.delawarebusinesstimes.com/
846,RV,2017-03-20,美国小型股由强转弱，受特朗普经济政策悬而未决拖累,http://wsj.com/,NEWSPAPER,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",美国小型股由强转弱，受特朗普经济政策悬而未决拖累,...减税和基础设施支出措施。这些计划往往有利于规模较小、更加关注美国国内市场的公司，而不是...,http://www.cn.wsj.com/gb/20170320/mkt140806.asp
847,RV,2017-03-20,美国小型股由强转弱，受特朗普经济政策悬而未决拖累,http://wsj.com/,NEWSPAPER,0,497014,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",美国小型股由强转弱，受特朗普经济政策悬而未决拖累,...减税和基础设施支出措施。这些计划往往有利于规模较小、更加关注美国国内市场的公司，而不是...,http://cn.wsj.com/gb/20170320/mkt140806.asp
848,RV,2017-03-20,美國小型股由強轉弱，受特朗普經濟政策懸而未決拖纍,http://wsj.com/,NEWSPAPER,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",美國小型股由強轉弱，受特朗普經濟政策懸而未決拖纍,...減稅和基礎設施支出措施。這些計劃往往有利於規模較小、更加關注美國國內市場的公司，而不是...,http://www.cn.wsj.com/Big5/20170320/mkt140806.asp
849,RV,2017-03-20,美國小型股由強轉弱，受特朗普經濟政策懸而未決拖纍,http://wsj.com/,NEWSPAPER,0,497014,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",美國小型股由強轉弱，受特朗普經濟政策懸而未決拖纍,...減稅和基礎設施支出措施。這些計劃往往有利於規模較小、更加關注美國國內市場的公司，而不是...,http://cn.wsj.com/Big5/20170320/mkt140806.asp
850,RV,2017-03-20,0,http://dailyherald.com/,OTHER,0,0,1,0,0,...,0,0,0,0,0,0,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Deer Park Town Center,"Morrison, Mr. and Mrs. J. Christopher Reyes, L...",http://local.dailyherald.com/deer-park-il/arts...
851,AG,2017-03-30,0,http://equities.com/,OTHER,0,230769,1,0,0,...,0,0,0,0,0,0,"SEARCH / Client / Wilmington Trust,PANEL / Tie...",MENTOR GRAPHICS CORP FILES (8-K) Disclosing En...,News\n\nMENTOR GRAPHICS CORP FILES (8-K) Discl...,http://www.equities.com/

In [5]:
table.Date = pd.to_datetime(table.Date)

In [7]:
table.columns

Index([u'Scorer', u'Date', u'Article Headline', u'Outlet/Publication',
       u'Post Type', u'Engagement', u'Reach', u'Trash', u'Press Release',
       u'Stocks', u'Scored', u'Questions/Comments', u'Wilmington Trust',
       u'Bessemer Trust', u'Northern Trust', u'PNC Wealth Management',
       u'SunTrust', u'Positive', u'Neutral', u'Negative',
       u' 1 = Single Mention              2 = Product/ Service Advocacy            3 = Thought Leadership         4 = Feature',
       u'1 = Tier1,  2 = Tier2,  3 = Tier3', u'Trusts',
       u'Economic Environment', u'Wealth Management', u'Market Environment',
       u'Trump/Administration Changes', u'Blockchain/ Technology', u'Brexit',
       u'TBD', u'Aubrey McClendon', u'Election Coverage', u'matched_profile',
       u'title', u'content', u'url'],
      dtype='object')

In [8]:
numeric_table = table[[u'Engagement', u'Reach', u'Trash', u'Press Release', u'Stocks', u'Scored',
       u'Wilmington Trust',
       u'Bessemer Trust', u'Northern Trust', u'PNC Wealth Management',
       u'SunTrust', u'Positive', u'Neutral', u'Negative',
       u' 1 = Single Mention              2 = Product/ Service Advocacy            3 = Thought Leadership         4 = Feature',
       u'1 = Tier1,  2 = Tier2,  3 = Tier3', u'Trusts',
       u'Economic Environment', u'Wealth Management', u'Market Environment',
       u'Trump/Administration Changes', u'Blockchain/ Technology', u'Brexit']].fillna(value = '0').astype(int)

In [9]:
table_ex = table.drop([ u'Engagement', u'Reach', u'Trash', u'Press Release', u'Stocks', u'Scored',
       u'Wilmington Trust',
       u'Bessemer Trust', u'Northern Trust', u'PNC Wealth Management',
       u'SunTrust', u'Positive', u'Neutral', u'Negative',
       u' 1 = Single Mention              2 = Product/ Service Advocacy            3 = Thought Leadership         4 = Feature',
       u'1 = Tier1,  2 = Tier2,  3 = Tier3', u'Trusts',
       u'Economic Environment', u'Wealth Management', u'Market Environment',
       u'Trump/Administration Changes', u'Blockchain/ Technology', u'Brexit'], axis = 1)

In [10]:
pd.set_option('display.max_columns', 500)

In [11]:
frames = [numeric_table, table_ex]
Master_Grid = pd.concat(frames, axis = 1)
ContentQuality = ' 1 = Single Mention              2 = Product/ Service Advocacy            3 = Thought Leadership         4 = Feature'
MediaQuality = '1 = Tier1,  2 = Tier2,  3 = Tier3'
PressRelease = 'Press Release'
Master_Grid

,Engagement,Reach,Trash,Press Release,Stocks,Scored,Wilmington Trust,Bessemer Trust,Northern Trust,PNC Wealth Management,SunTrust,Positive,Neutral,Negative,1 = Single Mention 2 = Product/ Service Advocacy 3 = Thought Leadership 4 = Feature,"1 = Tier1, 2 = Tier2, 3 = Tier3",Trusts,Economic Environment,Wealth Management,Market Environment,Trump/Administration Changes,Blockchain/ Technology,Brexit,Scorer,Date,Article Headline,Outlet/Publication,Post Type,Questions/Comments,TBD,Aubrey McClendon,Election Coverage,matched_profile,title,content,url
0,2,80000,0,0,0,1,0,1,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,CM,2017-01-27,National Housing Equity Investor Renews 18K-SF...,http://commercialobserver.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Bessemer Trust,PANEL / Tier 1 - UP...",National Housing Equity Investor Renews 18K-SF...,...and is known as the International Building ...,https://commercialobserver.com/2017/01/nationa...
1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,3,1,0,0,0,1,1,0,0,CM,2017-01-18,Patterson: This is going to be the year with a...,http://yahoo.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Bessemer Trust,PANEL / Tier 1 - UP...",Patterson: This is going to be the year with a...,"Rebecca Patterson, Bessemer Trust managing dir...",https://hk.finance.yahoo.com/video/patterson-g...
2,128,1272195,0,0,0,1,0,1,0,0,0,1,0,0,3,1,0,0,0,1,1,0,0,CM,2017-01-17,Patterson: This is going to be the year with a...,http://cnbc.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Bessemer Trust,PANEL / Tier 1 - UP...",Patterson: This is going to be the year with a...,...be the year with a lot of push and pull\n\n...,http://video.cnbc.com/gallery/?video=3000585316
3,0,5585366,0,0,0,1,0,1,0,0,0,1,0,0,3,2,0,0,0,1,1,0,0,CM,2017-01-18,Patterson: This is going to be the year with a...,http://nasdaq.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Bessemer Trust,PANEL / Tier 2 - UP...",Patterson: This is going to be the year with a...,"Rebecca Patterson, Bessemer Trust managing dir...",http://www.nasdaq.com/video/587fb34b1c689973d4...
4,179,95652,1,0,0,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,JC,2017-01-25,‘Great rotation’ highlights clash over unseen ...,http://risk.net/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",‘Great rotation’ highlights clash over unseen ...,"...Northern Trust Asset Management in Chicago,...",http://www.risk.net/risk/feature/2480714/-grea...
5,227,679012,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,RS,2017-01-09,Aries Capital merges mortgage banking business...,http://chicagobusiness.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Aries Capital merges mortgage banking business...,...al property financing businesses in the cou...,http://www.chicagobusiness.com/realestate/2017...
6,0,0,0,0,0,1,0,1,0,0,0,1,0,0,3,1,0,0,0,1,1,0,0,CM,2017-01-10,Politics and earnings are the biggest risks to...,http://yahoo.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Bessemer Trust,PANEL / Tier 1 - UP...",Politics and earnings are the biggest risks to...,"Chris Cordaro, RegentAtlantic Capital, and Reb...",https://hk.finance.yahoo.com/video/politics-ea...
7,1,8698979,1,0,0,0,0,0,0,0,1,0,0,0,0,2,0,0,0,0,0,0,0,RS,2017-01-20,"January 20, 2017 Legal notices - Orlando Busin...",http://bizjournals.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...","January 20, 2017 Legal notices - Orlando Busin...","...and Investor Trustee\n\nServices, Llcas Tru...",http://www.bizjournals.com/orlando/resources/l...
8,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,2,0,0,0,0,0,0,0,RS,2017-01-20,"January 20, 2017 Legal notices - Orlando Busin...",http://bizjournals.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...","January 20, 2017 Legal notices - Orlando Busin...","...and Investor Trustee\n\nServices, Llcas Tru...",http://assets-origin.bizjournals.com/orlando/r...
9,0,177254,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-10,《美国上市公司业绩公布日程表》--1月11日至1月18日,http://reuters.com/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月11日至1月18日,Bancorp) 1月18日 BMO SCHW.N Q4 2016 嘉信理财(Charles...,http://cn.reuters.com/article/idCNL4S1F11JC
10,0,177254,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-11,《美国上市公司业绩公布日程表》--1月12日至1月19日,http://reuters.com/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月12日至1月19日,...Schwab) 1月18日 BMO NTRS.OQ Q4 2016 Northern ...,http://cn.reuters.com/article/idCNL4S1F21WS?fe...
11,0,177254,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-12,《美国上市公司业绩公布日程表》--1月13日至1月20日,http://reuters.com/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月13日至1月20日,...Schwab) 1月18日 BMO NTRS.OQ Q4 2016 Northern ...,http://cn.reuters.com/article/idCNL4S1F31XI
12,0,177254,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-15,《美国上市公司业绩公布日程表》--1月16日至1月23日,http://reuters.com/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月16日至1月23日,...2017-01-18 BMO NTRS.OQ Q4 2016 Northern Tru...,http://cn.reuters.com/article/idCNL4S1F61PN
13,0,177254,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-16,《美国上市公司业绩公布日程表》--1月17日至1月24日,http://reuters.com/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月17日至1月24日,...2017-01-18 BMO NTRS.OQ Q4 2016 Northern Tru...,http://cn.reuters.com/article/idCNL4S1F71IY
14,0,177254,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-17,《美国上市公司业绩公布日程表》--1月18日至1月25日,http://reuters.com/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",《美国上市公司业绩公布日程表》--1月18日至1月25日,...2017-01-18 BMO NTRS.OQ Q4 2016 Northern Tru...,http://cn.reuters.com/article/idCNL4S1F81LA
15,5,556086,0,0,0,1,0,0,1,0,0,1,0,0,3,1,0,0,1,1,1,0,0,JC,2017-01-31,3 Stocks To Sell If Trump Names Japan A Curren...,http://barrons.com/,BLOG,not sure if relevant -- check w/ Abby,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",3 Stocks To Sell If Trump Names Japan A Curren...,\n\nWorrying that Trump may shift his harsh cu...,http://blogs.barrons.com/asiastocks/2017/01/31...
16,4,36318,0,0,0,1,0,0,1,0,0,1,0,0,3,1,0,1,0,0,0,0,0,JC,2017-01-10,A batalha das montadoras para sobreviver na er...,http://wsj.com/,NEWSPAPER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",A batalha das montadoras para sobreviver na er...,...não parecem ser candidatos óbvios. Neil Cam...,http://br.wsj.com/articles/SB12742076995748244...
17,0,3462874,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://ap.org/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://hosted.ap.org/dynamic/stories/F/FINANCI...
18,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://ap.org/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://akamai.hosted.ap.org/dynamic/stories/F/...
19,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://yahoo.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",https://nz.finance.yahoo.com/news/adobe-coluci...
20,0,130259256,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma Edge Higher While Tar...,http://nytimes.com/,NEWSPAPER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma Edge Higher While Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.nytimes.com/aponline/2017/01/18/bus...
21,0,224299,1,0,0,0,0,0,1,0,0,0,0,0,0,3,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://bradenton.com/,NEWSPAPER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.bradenton.com/news/business/article...
22,0,196969,1,0,0,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://equities.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million ....",https://www.equities.com/news/adobe-and-coluci...
23,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://kansascity.com/,NEWSPAPER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://qa1.kansascity.com/news/business/nation...
24,0,32606720,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://yahoo.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://finance.yahoo.com/news/adobe-colucid-ph...
25,0,10341176,1,0,0,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://salon.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.salon.com/2017/01/18/adobe-and-colu...
26,0,1628205,1,0,0,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://kansascity.com/,NEWSPAPER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.kansascity.com/news/business/nation...
27,0,3221557,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,JC,2017-01-18,Adobe and CoLucid Pharma edge higher while Tar...,http://ap.org/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://bigstory.ap.org/article/e5da639891be4ff...
28,0,4757009,1,0,0,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,JC,2017-01-17,Adobe and CoLucid Pharma edge higher while Tar...,http://startribune.com/,NEWSPAPER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Adobe and CoLucid Pharma edge higher while Tar...,"...Lilly for $46.50 a share, or $895 million.\...",http://www.startribune.com/adobe-and-colucid-p...
29,18,41176,1,0,0,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,JC,2017-01-16,AFTAs 2016 ─ All the Winners and Why They Won,http://waterstechnology.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",AFTAs 2016 ─ All the Winners and Why They Won,"...executive, sell side); Scott Murray (Northe...",http://www.waterstechnology.com/waters/news/24...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,26,7383721,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-30,SunTrust taps Jenna Kelly to lead Atlanta Divi...,http://bizjournals.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",SunTrust taps Jenna Kelly to lead Atlanta Divi...,"...to Financial Well-Being ' for our clients,""...",http://www.bizjournals.com/atlanta/news/2017/0...
823,0,1140000,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-21,SunTrust: Small and Mid-market Business Bullis...,http://benzinga.com/,BLOG,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 1 - UPDATED ...",SunTrust: Small and Mid-market Business Bullis...,"...credit, trust, investment, mortgage, asset ...",https://www.benzinga.com/pressreleases/17/03/n...
824,0,909,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-21,SunTrust: Small and Mid-market Business Bullis...,http://itbusinessnet.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",SunTrust: Small and Mid-market Business Bullis...,"...deposit, credit, trust, investment, mortgag...",http://business.itbusinessnet.com/article/SunT...
825,0,118181,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-21,SunTrust: Small and Mid-market Business Bullis...,http://itbusinessnet.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",SunTrust: Small and Mid-market Business Bullis...,"...deposit, credit, trust, investment, mortgag...",http://www.itbusinessnet.com/articles/viewarti...
826,0,2727,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-21,SunTrust: Small and Mid-market Business Bullis...,http://itbusinessnet.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",SunTrust: Small and Mid-market Business Bullis...,"...deposit, credit, trust, investment, mortgag...",http://security.itbusinessnet.com/article/SunT...
827,0,13809524,0,0,0,1,0,0,1,0,0,1,0,0,2,1,0,0,0,1,0,0,0,RV,2017-03-20,TechIBM Launches New Cloud Service for Buildin...,http://fortune.com/,BLOG,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",TechIBM Launches New Cloud Service for Buildin...,"...including Northern Trust, [f500link]Wal-Mar...",http://fortune.com/go/tech/ibm-blockchain-serv...
828,0,1023809,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,AG,2017-03-31,Turkish Construction Giant Hit with $237M Unpa...,http://law360.com/,OTHER,can't read,NaN,NaN,NaN,"SEARCH / Client / Wilmington Trust,PANEL / Tie...",Turkish Construction Giant Hit with $237M Unpa...,"Law360, London (March 31, 2017, 5:28 PM BST) -...",http://www.law360.com/
829,0,44879228,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-24,UPDATE 1-Carlyle extends private equity oil ru...,http://reuters.com/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",UPDATE 1-Carlyle extends private equity oil ru...,...\nFunds News\n\nCORRECTED-Fed gives Norther...,http://www.reuters.com/article/shell-carlyle-g...
830,0,44879228,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-24,UPDATE 1-Fed gives four foreign banks 'living ...,http://reuters.com/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,SEARCH / / SunTrus...",UPDATE 1-Fed gives four foreign banks 'living ...,"...One Financial Corp, Comerica Inc, Discover ...",http://www.reuters.com/article/usa-fed-livingw...
831,0,1194035,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-24,UPDATE 1-Fed gives four foreign banks 'living ...,http://investing.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",UPDATE 1-Fed gives four foreign banks 'living ...,"...'living will' extension, faults Northern Tr...",https://in.investing.com/news/stock-market-new...
832,0,465189,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-24,UPDATE 1-Fed gives four foreign banks 'living ...,http://businessinsider.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 1 - UPDATED ...",UPDATE 1-Fed gives four foreign banks 'living ...,"...Ally Financial Inc, BB&T Corp, Capital One ...",http://markets.businessinsider.com/news/stocks...
833,0,44879228,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-24,UPDATE 1-N.Y. Fed raises U.S. Q1 GDP estimate ...,http://reuters.com/,AGENCY,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",UPDATE 1-N.Y. Fed raises U.S. Q1 GDP estimate ...,"...four foreign banks 'living will' extension,...",http://www.reuters.com/article/usa-economy-nyf...
834,20,7383721,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-22,"Walter Investment Management (NYSE: WAC), Cent...",http://bizjournals.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...","Walter Investment Management (NYSE: WAC), Cent...","...Ablin , chief investment officer at BMO Pri...",http://www.bizjournals.com/tampabay/news/2017/...
835,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-22,"Walter Investment Management (NYSE: WAC), Cent...",http://bizjournals.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...","Walter Investment Management (NYSE: WAC), Cent...","...Ablin , chief investment officer at BMO Pri...",http://assets-origin.bizjournals.com/tampabay/...
836,6,76470,0,0,0,1,0,0,1,0,0,1,0,0,3,2,0,1,0,0,1,0,0,RV,2017-03-21,Waning Confidence in Trump Trade Drags on Stoc...,http://etftrends.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Waning Confidence in Trump Trade Drags on Stoc...,"...forefront of investors’ minds,” Katie Nixon...",http://www.etftrends.com/2017/03/waning-confid...
837,15,930000,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-18,Welcome to the WSO Company Database. | Wall St...,http://wallstreetoasis.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",Welcome to the WSO Company Database. | Wall St...,...independent financial investment firm that ...,https://www.wallstreetoasis.com/wso-company-da...
838,0,7383721,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-28,Wells Fargo (NYSE: WFC) agrees to $110 million...,http://bizjournals.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",Wells Fargo (NYSE: WFC) agrees to $110 million...,"1, 2009 to the settlement date.\n\nThe court m...",http://www.bizjournals.com/orlando/news/2017/0...
839,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-28,Wells Fargo (NYSE: WFC) agrees to $110 million...,http://bizjournals.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / SunTrust,PANEL / Tier 2 - UPDATED ...",Wells Fargo (NYSE: WFC) agrees to $110 million...,"1, 2009 to the settlement date.\n\nThe court m...",http://assets-origin.bizjournals.com/orlando/n...
840,170,16299213,0,0,0,1,0,0,1,0,0,0,1,0,1,1,0,0,0,0,0,1,0,RV,2017-03-20,What Is Blockchain? IBM Launches Service For E...,http://ibtimes.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 1 - UP...",What Is Blockchain? IBM Launches Service For E...,...provider SecureKey; financial services comp...,http://www.ibtimes.com/what-blockchain-ibm-lau...
841,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-24,What’s next for infill around the Valley?,http://bizjournals.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",What’s next for infill around the Valley?,"...\nAlready taking space: State Farm, Norther...",http://assets-origin.bizjournals.com/phoenix/n...
842,13,7383721,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,RV,2017-03-24,What’s next for infill around the Valley?,http://bizjournals.com/,MAGAZINE,NaN,NaN,NaN,NaN,"SEARCH / / Northern Trust,PANEL / Tier 2 - UP...",What’s next for infill around the Valley?,"...\nAlready taking space: State Farm, Norther...",http://www.bizjournals.com/phoenix/news/2017/0...
843,0,0,0,0,0,1,1,0,0,0,0,1,0,0,2,2,1,0,0,0,0,0,0,AG,2017-03-24,Wilmington Trust to oversee $2.7B Volkswagen t...,http://delawareonline.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / Client / Wilmington Trust,PANEL / Tie...",Wilmington Trust to oversee $2.7B Volkswagen t...,Wilmington Trust will serve as the trustee of ...,http://ux.delawareonline.com/
844,1,500000,0,0,0,1,1,0,0,0,0,1,0,0,2,2,1,0,0,0,0,0,0,AG,2017-03-24,Wilmington Trust to oversee $2.7B Volkswagen t...,http://delawareonline.com/,OTHER,NaN,NaN,NaN,NaN,"SEARCH / Client / Wilmington Trust,PANEL / Tie...",Wilmington Trust to oversee $2.7B Volkswagen t...,Wilmington Trust will serve as the trustee of ...,http://www.delawareonline.com/

In [56]:
Competitor_SOV = Master_Grid[Master_Grid['Scored']==1].sum()
Competitor_SOV = pd.DataFrame(Competitor_SOV['Wilmington Trust':'SunTrust'], columns = ['Share of Voice'])
Competitor_SOV['Percentage'] = (Competitor_SOV['Share of Voice']/Competitor_SOV['Share of Voice'].sum())
Competitor_SOV

                       Share of Voice  Percentage
Wilmington Trust                 13.0    0.044369
Bessemer Trust                   37.0    0.126280
Northern Trust                  208.0    0.709898
PNC Wealth Management             3.0    0.010239
SunTrust                         32.0    0.109215

In [57]:
Topics_SOV = Master_Grid[Master_Grid['Scored']==1].sum()
Topics_SOV = pd.DataFrame(Topics_SOV['Trusts':'Market Environment'], columns = ['Share of Voice'])
Topics_SOV['Percentage'] = (Topics_SOV['Share of Voice']/Topics_SOV['Share of Voice'].sum())
Topics_SOV

                      Share of Voice  Percentage
Trusts                           7.0    0.038462
Economic Environment            46.0    0.252747
Wealth Management               33.0    0.181319
Market Environment              96.0    0.527473

In [58]:
Tonality_SOV = pd.DataFrame([['Positive',Master_Grid['Positive'].sum()],['Neutral',Master_Grid['Neutral'].sum()],['Negative',Master_Grid['Negative'].sum()]], columns = ['Tonality SOV', 'Total'])
Tonality_SOV['Percentage'] = (Tonality_SOV['Total']/Tonality_SOV['Total'].sum())
Tonality_SOV

  Tonality SOV  Total  Percentage
0     Positive    166    0.566553
1      Neutral    108    0.368601
2     Negative     19    0.064846

In [59]:
Positive = Master_Grid[Master_Grid['Positive']==1].sum()
PositiveDF = pd.DataFrame(Positive['Wilmington Trust':'SunTrust'])
PositiveDF = PositiveDF.rename(columns = {0:'Positive'})
PositiveDF['Percentage'] = (PositiveDF['Positive']/PositiveDF['Positive'].sum())
PositiveDF

                       Positive  Percentage
Wilmington Trust            7.0    0.041916
Bessemer Trust             26.0    0.155689
Northern Trust            125.0    0.748503
PNC Wealth Management       2.0    0.011976
SunTrust                    7.0    0.041916

In [60]:

Neutral = Master_Grid[Master_Grid['Neutral']==1].sum()
NeutralDF = pd.DataFrame(Neutral['Wilmington Trust':'SunTrust'])
NeutralDF = NeutralDF.rename(columns = {0:'Neutral'})
NeutralDF['Percentage'] = (NeutralDF['Neutral']/NeutralDF['Neutral'].sum())
NeutralDF

                       Neutral  Percentage
Wilmington Trust           4.0    0.037037
Bessemer Trust            11.0    0.101852
Northern Trust            70.0    0.648148
PNC Wealth Management      4.0    0.037037
SunTrust                  19.0    0.175926

In [61]:
Negative = Master_Grid[Master_Grid['Negative']==1].sum()
NegativeDF = pd.DataFrame(Negative['Wilmington Trust':'SunTrust'])
NegativeDF = NegativeDF.rename(columns = {0:'Negative'})
NegativeDF['Percentage'] = (NegativeDF['Negative']/NegativeDF['Negative'].sum())
NegativeDF

                       Negative  Percentage
Wilmington Trust            2.0    0.086957
Bessemer Trust              0.0    0.000000
Northern Trust             15.0    0.652174
PNC Wealth Management       0.0    0.000000
SunTrust                    6.0    0.260870

In [62]:
content_list=[]
for i in range(1,5):
    list1 = Master_Grid[Master_Grid[ContentQuality]==i].shape[0]
    pd.DataFrame(content_list.append(list1))
df = pd.DataFrame(content_list) 
Content_Quality = df.rename(columns = {0:'Content Quality'},  index = {0:'Single Mention',1:'Product/ Service Advocacy', 2:'Thought Leadership', 3:'Feature'})
Content_Quality['Percentage'] = (Content_Quality['Content Quality']/Content_Quality['Content Quality'].sum())
Content_Quality

                           Content Quality  Percentage
Single Mention                          57    0.193878
Product/ Service Advocacy               22    0.074830
Thought Leadership                     175    0.595238
Feature                                 40    0.136054

In [63]:
SingleMention = Master_Grid[Master_Grid[ContentQuality]==1].sum()
SingleMentionDF = pd.DataFrame(SingleMention['Wilmington Trust':'SunTrust'])
SingleMentionDF = SingleMentionDF.rename(columns = {0:'Single Mention'})
SingleMentionDF['Percentage'] = (SingleMentionDF['Single Mention']/SingleMentionDF['Single Mention'].sum())
SingleMentionDF

                       Single Mention  Percentage
Wilmington Trust                  3.0    0.051724
Bessemer Trust                    1.0    0.017241
Northern Trust                   42.0    0.724138
PNC Wealth Management             0.0    0.000000
SunTrust                         12.0    0.206897

In [64]:
MiddleMention = Master_Grid[Master_Grid[ContentQuality]==2].sum()
MiddleMentionDF = pd.DataFrame(MiddleMention['Wilmington Trust':'SunTrust'])
MiddleMentionDF = MiddleMentionDF.rename(columns = {0:'Middle Mention'})
#MiddleMentionDF['Percentage'] = (MiddleMentionDF['Middle Mention']/PSAdvocacyDF['Middle Mention'].sum())
MiddleMentionDF

                       Middle Mention
Wilmington Trust                  4.0
Bessemer Trust                    0.0
Northern Trust                   18.0
PNC Wealth Management             0.0
SunTrust                          0.0

In [65]:
ThoughtLeadership = Master_Grid[Master_Grid[ContentQuality]==3].sum()
ThoughtLeadershipDF = pd.DataFrame(ThoughtLeadership['Wilmington Trust':'SunTrust'])
ThoughtLeadershipDF = ThoughtLeadershipDF.rename(columns = {0:'Thought Leadership'})
ThoughtLeadershipDF['Percentage'] = (ThoughtLeadershipDF['Thought Leadership']/ThoughtLeadershipDF['Thought Leadership'].sum())
ThoughtLeadershipDF

                       Thought Leadership  Percentage
Wilmington Trust                      5.0    0.028571
Bessemer Trust                       29.0    0.165714
Northern Trust                      124.0    0.708571
PNC Wealth Management                 5.0    0.028571
SunTrust                             12.0    0.068571

In [66]:
Feature = Master_Grid[Master_Grid[ContentQuality]==4].sum()
FeatureDF = pd.DataFrame(Feature['Wilmington Trust':'SunTrust'])
FeatureDF = FeatureDF.rename(columns = {0:'Feature'})
FeatureDF['Percentage'] = (FeatureDF['Feature']/FeatureDF['Feature'].sum())
FeatureDF

                       Feature  Percentage
Wilmington Trust           1.0    0.022727
Bessemer Trust             7.0    0.159091
Northern Trust            27.0    0.613636
PNC Wealth Management      1.0    0.022727
SunTrust                   8.0    0.181818

In [67]:
T1 = Master_Grid[Master_Grid[MediaQuality]==1].sum()
T1DF = pd.DataFrame([T1['Wilmington Trust':'SunTrust']])
T1DF = T1DF.T
T1DF = T1DF.rename(columns = {0:'Tier 1'})
T1DF1 = pd.DataFrame(T1DF)
T1DF1['Key'] = (['key1','key2','key3','key4','key5'])

T2 = Master_Grid[Master_Grid[MediaQuality]==2].sum()
T2DF = pd.DataFrame([T2['Wilmington Trust':'SunTrust']])
T2DF = T2DF.T
T2DF = T2DF.rename(columns = {0:'Tier 2'})
T2DF1 = pd.DataFrame(T2DF)
T2DF1['Key'] = (['key1','key2','key3','key4','key5'])


merge1 = pd.merge(T1DF1, T2DF1, how = 'right', on = ['Key'])

merge = merge1.rename(index = {0:'Wilmington Trust',1:'Bessemer Trust', 2:'Corporation services', 3:'PNC Wealth Management', 4:'SunTrust'})
MQ = merge.drop(['Key'], axis = 1)
MQ

                       Tier 1  Tier 2
Wilmington Trust          7.0    22.0
Bessemer Trust           32.0     8.0
Corporation services    226.0   191.0
PNC Wealth Management     6.0     3.0
SunTrust                 42.0    72.0

In [68]:
MQ.iloc[:,0][1]

32.0

In [69]:
Trusts = Master_Grid[Master_Grid['Trusts']==1].sum()
TrustsDF = pd.DataFrame([Trusts['Wilmington Trust':'SunTrust']])
TrustsDF = TrustsDF.T
TrustsDF = TrustsDF.rename(columns = {0:'Trusts'})
TrustsDF1 = pd.DataFrame(TrustsDF)
TrustsDF1['Key'] = (['key1','key2','key3','key4','key5'])
Ecoenv = Master_Grid[Master_Grid['Economic Environment']==1].sum()
EcoenvDF = pd.DataFrame([Ecoenv['Wilmington Trust':'SunTrust']])
EcoenvDF = EcoenvDF.T
EcoenvDF = EcoenvDF.rename(columns = {0:'Economic Environment'})
EcoenvDF1 = pd.DataFrame(EcoenvDF)
EcoenvDF1['Key'] = (['key1','key2','key3','key4','key5'])
WealthMgmt = Master_Grid[Master_Grid['Wealth Management']==1].sum()
WealthMgmtDF = pd.DataFrame([WealthMgmt['Wilmington Trust':'SunTrust']])
WealthMgmtDF = WealthMgmtDF.T
WealthMgmtDF1 = WealthMgmtDF.rename(columns = {0:'Wealth Management'})
WealthMgmtDF1['Key'] = (['key1','key2','key3','key4','key5'])
MrkEnv = Master_Grid[Master_Grid['Market Environment']==1].sum()
MrkEnvDF = pd.DataFrame([MrkEnv['Wilmington Trust':'SunTrust']])
MrkEnvDF = MrkEnvDF.T
MrkEnvDF1 = MrkEnvDF.rename(columns = {0:'Market Environment'})
MrkEnvDF1['Key'] = (['key1','key2','key3','key4','key5'])


merge1 = pd.merge(TrustsDF1, EcoenvDF1, how = 'right', on = ['Key'])
merge2 = pd.merge(merge1, WealthMgmtDF1, how = 'right', on = ['Key'])
merge3 = pd.merge(merge2, MrkEnvDF1, how = 'right', on = ['Key'])

merge = merge3.rename(index = {0:'Wilmington Trust',1:'Bessemer Trust', 2:'Corporation services', 3:'PNC Wealth Management', 4:'SunTrust'})
Com_Analysis = merge.drop(['Key'], axis = 1)
Com_Analysis

,Trusts,Economic Environment,Wealth Management,Market Environment
Wilmington Trust,4.0,3.0,2.0,2.0
Bessemer Trust,0.0,2.0,1.0,19.0
Corporation services,3.0,40.0,24.0,70.0
PNC Wealth Management,0.0,2.0,0.0,0.0
SunTrust,0.0,1.0,6.0,5.0

In [70]:
Grid = Master_Grid[Master_Grid['Scored']==1]
content_list = []
for i in range(1,5):
    list1 = Grid[Grid[ContentQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
CQ1 = df.rename(columns = {0:'Content Quality'}, index = {0:'Single Mention',1:'Middle Mention', 2:'Thought Leadership', 3:'Feature'})
CQ1['Percentage'] = (CQ1['Content Quality']/CQ1['Content Quality'].sum())
CQ1

                    Content Quality  Percentage
Single Mention                   57    0.197917
Middle Mention                   22    0.076389
Thought Leadership              169    0.586806
Feature                          40    0.138889

In [71]:
SM = Master_Grid[Master_Grid[ContentQuality]==1].sum()
SMDF = pd.DataFrame([SM['Wilmington Trust':'SunTrust']])
SMDF = SMDF.T
SMDF = SMDF.rename(columns = {0:'Single Mention'})
SMDF1 = pd.DataFrame(SMDF)
SMDF1['Key'] = (['key1','key2','key3','key4','key5'])
MM = Master_Grid[Master_Grid[ContentQuality]==2].sum()
MMDF = pd.DataFrame([MM['Wilmington Trust':'SunTrust']])
MMDF = MMDF.T
MMDF = MMDF.rename(columns = {0:'Middle Mention'})
MMDF1 = pd.DataFrame(MMDF)
MMDF1['Key'] = (['key1','key2','key3','key4','key5'])
TL = Master_Grid[Master_Grid[ContentQuality]==3].sum()
TLDF = pd.DataFrame([TL['Wilmington Trust':'SunTrust']])
TLDF = TLDF.T
TLDF1 = TLDF.rename(columns = {0:'Thougth Leadership'})
TLDF1['Key'] = (['key1','key2','key3','key4','key5'])
F = Master_Grid[Master_Grid[ContentQuality]==4].sum()
FDF = pd.DataFrame([F['Wilmington Trust':'SunTrust']])
FDF = FDF.T
FDF1 = FDF.rename(columns = {0:'Feature'})
FDF1['Key'] = (['key1','key2','key3','key4','key5'])


merge1 = pd.merge(SMDF1, MMDF1, how = 'right', on = ['Key'])
merge2 = pd.merge(merge1, TLDF1, how = 'right', on = ['Key'])
merge3 = pd.merge(merge2, FDF1, how = 'right', on = ['Key'])

merge = merge3.rename(index = {0:'Wilmington Trust',1:'Bessemer Trust', 2:'Corporation services', 3:'PNC Wealth Management', 4:'SunTrust'})
CQ = merge.drop(['Key'], axis = 1)
CQ

,Single Mention,Middle Mention,Thougth Leadership,Feature
Wilmington Trust,3.0,4.0,5.0,1.0
Bessemer Trust,1.0,0.0,29.0,7.0
Corporation services,42.0,18.0,124.0,27.0
PNC Wealth Management,0.0,0.0,5.0,1.0
SunTrust,12.0,0.0,12.0,8.0

In [72]:
CQ.iloc[:,0][2]

42.0

In [73]:
Trusts = Master_Grid[Master_Grid['Trusts']==1].sum()
TrustsDF = pd.DataFrame([Trusts['Wilmington Trust':'SunTrust']])
TrustsDF = TrustsDF.T
TrustsDF = TrustsDF.rename(columns = {0:'Trusts'})
TrustsDF['Percentage'] = (TrustsDF['Trusts']/TrustsDF['Trusts'].sum())
TrustsDF

                       Trusts  Percentage
Wilmington Trust          4.0    0.571429
Bessemer Trust            0.0    0.000000
Northern Trust            3.0    0.428571
PNC Wealth Management     0.0    0.000000
SunTrust                  0.0    0.000000

In [74]:
Ecoenv = Master_Grid[Master_Grid['Economic Environment']==1].sum()
EcoenvDF = pd.DataFrame([Ecoenv['Wilmington Trust':'SunTrust']])
EcoenvDF = EcoenvDF.T
EcoenvDF = EcoenvDF.rename(columns = {0:'Economic Environment'})
EcoenvDF['Percentage'] = (EcoenvDF['Economic Environment']/EcoenvDF['Economic Environment'].sum())
EcoenvDF

                       Economic Environment  Percentage
Wilmington Trust                        3.0    0.062500
Bessemer Trust                          2.0    0.041667
Northern Trust                         40.0    0.833333
PNC Wealth Management                   2.0    0.041667
SunTrust                                1.0    0.020833

In [75]:
MrkEnv = Master_Grid[Master_Grid['Market Environment']==1].sum()
MrkEnvDF = pd.DataFrame([MrkEnv['Wilmington Trust':'SunTrust']])
MrkEnvDF = MrkEnvDF.T
MrkEnvDF = MrkEnvDF.rename(columns = {0:'Market Environment'})
MrkEnvDF['Percentage'] = (MrkEnvDF['Market Environment']/MrkEnvDF['Market Environment'].sum()) 
MrkEnvDF

                       Market Environment  Percentage
Wilmington Trust                      2.0    0.020833
Bessemer Trust                       19.0    0.197917
Northern Trust                       70.0    0.729167
PNC Wealth Management                 0.0    0.000000
SunTrust                              5.0    0.052083

In [77]:
WealthMgmt = Master_Grid[(Master_Grid['Wealth Management']==1) & (Master_Grid['Positive']==1)].sum()
WealthMgmtDF = pd.DataFrame([WealthMgmt['Wilmington Trust':'SunTrust']])
WealthMgmtDF = WealthMgmtDF.T
WealthMgmtDF = WealthMgmtDF.rename(columns = {0:'Wealth Management'})
WealthMgmtDF['Percentage'] = (WealthMgmtDF['Wealth Management']/WealthMgmtDF['Wealth Management'].sum()) 
WealthMgmtDF
#WealthMgmt

                       Wealth Management  Percentage
Wilmington Trust                     2.0    0.076923
Bessemer Trust                       1.0    0.038462
Northern Trust                      19.0    0.730769
PNC Wealth Management                0.0    0.000000
SunTrust                             4.0    0.153846

In [78]:
WT_Topics = Master_Grid[Master_Grid['Wilmington Trust']==1].sum()
WT_TopicsDF = pd.DataFrame([WT_Topics['Trusts':'Market Environment']])
WT_TopicsDF = WT_TopicsDF.T
WT_TopicsDF = WT_TopicsDF.rename(columns = {0:'Topics'})
WT_TopicsDF['Percentage'] = WT_TopicsDF['Topics']/WT_TopicsDF['Topics'].sum()
WT_TopicsDF

                      Topics  Percentage
Trusts                   4.0    0.363636
Economic Environment     3.0    0.272727
Wealth Management        2.0    0.181818
Market Environment       2.0    0.181818

In [79]:
WT_Tonality = Master_Grid[Master_Grid['Wilmington Trust']==1].sum()
WT_TonalityDF = pd.DataFrame([WT_Tonality['Positive':'Negative']])
WT_TonalityDF = WT_TonalityDF.T
WT_TonalityDF = WT_TonalityDF.rename(columns = {0:'Tonality'})
WT_TonalityDF['Percentage'] = ((WT_TonalityDF['Tonality']/WT_TonalityDF['Tonality'].sum())*100)
WT_TonalityDF

          Tonality  Percentage
Positive       7.0   53.846154
Neutral        4.0   30.769231
Negative       2.0   15.384615

In [80]:
WT= Master_Grid[Master_Grid['Wilmington Trust']==1]
content_list = []
for i in range(1,5):
    list1 = WT[WT[ContentQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
WT_CQ = df.rename(columns = {0:'Content Quality'}, index = {0:'Single Mention',1:'Product/ Service Advocacy', 2:'Thought Leadership', 3:'Feature'})
WT_CQ['Percentage'] = (WT_CQ['Content Quality']/WT_CQ['Content Quality'].sum())
WT_CQ

                           Content Quality  Percentage
Single Mention                           3    0.230769
Product/ Service Advocacy                4    0.307692
Thought Leadership                       5    0.384615
Feature                                  1    0.076923

In [81]:
WT1 = Master_Grid[Master_Grid['Scored']==1]
WT = WT1[WT1['Wilmington Trust']==1]
content_list = []
for i in range(1,3):
    list1 = WT[WT[MediaQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
WT_MQ = df.rename(columns = {0:'Media Quality'}, index = {0:'Tier1', 1:'Tier2'})
WT_MQ['Percentage'] = (WT_MQ['Media Quality']/WT_MQ['Media Quality'].sum())
WT_MQ

       Media Quality  Percentage
Tier1              4    0.307692
Tier2              9    0.692308

In [82]:
BT_Topics = Master_Grid[Master_Grid['Bessemer Trust']==1].sum()
BT_TopicsDF = pd.DataFrame([BT_Topics['Trusts':'Market Environment']])
BT_TopicsDF = BT_TopicsDF.T
BT_TopicsDF = BT_TopicsDF.rename(columns = {0:'Topics'})
BT_TopicsDF['Percentage'] = (BT_TopicsDF['Topics']/BT_TopicsDF['Topics'].sum()) 
BT_TopicsDF

                      Topics  Percentage
Trusts                   0.0    0.000000
Economic Environment     2.0    0.090909
Wealth Management        1.0    0.045455
Market Environment      19.0    0.863636

In [83]:
BT_Tonality = Master_Grid[Master_Grid['Bessemer Trust']==1].sum()
BT_TonalityDF = pd.DataFrame([BT_Tonality['Positive':'Negative']])
BT_TonalityDF = BT_TonalityDF.T
BT_TonalityDF = BT_TonalityDF.rename(columns = {0:'Tonality'})
BT_TonalityDF['Percentage'] = (BT_TonalityDF['Tonality']/BT_TonalityDF['Tonality'].sum()) 
BT_TonalityDF

          Tonality  Percentage
Positive      26.0    0.702703
Neutral       11.0    0.297297
Negative       0.0    0.000000

In [84]:
BT = Master_Grid[Master_Grid['Bessemer Trust']==1]
content_list = []
for i in range(1,5):
    list1 = BT[BT[ContentQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
BT_CQ = df.rename(columns = {0:'Content Quality'}, index = {0:'Single Mention',1:'Middle Mention', 2:'Thought Leadership', 3:'Feature'})
BT_CQ['Percentage'] = (BT_CQ['Content Quality']/BT_CQ['Content Quality'].sum())
BT_CQ

                    Content Quality  Percentage
Single Mention                    1    0.027027
Middle Mention                    0    0.000000
Thought Leadership               29    0.783784
Feature                           7    0.189189

In [85]:
BT1 = Master_Grid[Master_Grid['Scored']==1]
BT = BT1[BT1['Bessemer Trust']==1]
content_list = []
for i in range(1,3):
    list1 = BT[BT[MediaQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
BT_MQ = df.rename(columns = {0:'Media Quality'}, index = {0:'Tier1', 1:'Tier2'})
BT_MQ['Percentage'] = (BT_MQ['Media Quality']/BT_MQ['Media Quality'].sum())
BT_MQ

       Media Quality  Percentage
Tier1             30    0.810811
Tier2              7    0.189189

In [86]:
NT_Topics = Master_Grid[Master_Grid['Northern Trust']==1].sum()
NT_TopicsDF = pd.DataFrame([NT_Topics['Trusts':'Market Environment']])
NT_TopicsDF = NT_TopicsDF.T
NT_TopicsDF = NT_TopicsDF.rename(columns = {0:'Topics'})
NT_TopicsDF['Percentage'] = (NT_TopicsDF['Topics']/NT_TopicsDF['Topics'].sum()) 
NT_TopicsDF

                      Topics  Percentage
Trusts                   3.0    0.021898
Economic Environment    40.0    0.291971
Wealth Management       24.0    0.175182
Market Environment      70.0    0.510949

In [87]:
NT_Tonality = Master_Grid[Master_Grid['Northern Trust']==1].sum()
NT_TonalityDF = pd.DataFrame([NT_Tonality['Positive':'Negative']])
NT_TonalityDF = NT_TonalityDF.T
NT_TonalityDF = NT_TonalityDF.rename(columns = {0:'Tonality'})
NT_TonalityDF['Percentage'] = (NT_TonalityDF['Tonality']/NT_TonalityDF['Tonality'].sum()) 
NT_TonalityDF

          Tonality  Percentage
Positive     125.0    0.595238
Neutral       70.0    0.333333
Negative      15.0    0.071429

In [88]:
NT = Master_Grid[Master_Grid['Northern Trust']==1]
content_list = []
for i in range(1,5):
    list1 = NT[NT[ContentQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
NT_CQ = df.rename(columns = {0:'Content Quality'}, index = {0:'Single Mention',1:'Middle Mention', 2:'Thought Leadership', 3:'Feature'})
NT_CQ['Percentage'] = (NT_CQ['Content Quality']/NT_CQ['Content Quality'].sum())
NT_CQ

                    Content Quality  Percentage
Single Mention                   42    0.199052
Middle Mention                   18    0.085308
Thought Leadership              124    0.587678
Feature                          27    0.127962

In [89]:
NT1 = Master_Grid[Master_Grid['Scored']==1]
NT = NT1[NT1['Northern Trust']==1]
content_list = []
for i in range(1,3):
    list1 = NT[NT[MediaQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
NT_MQ = df.rename(columns = {0:'Media Quality'}, index = {0:'Tier1', 1:'Tier2'})
NT_MQ['Percentage'] = (NT_MQ['Media Quality']/NT_MQ['Media Quality'].sum())
NT_MQ

       Media Quality  Percentage
Tier1            115    0.552885
Tier2             93    0.447115

In [90]:
PNC_Topics = Master_Grid[Master_Grid['PNC Wealth Management']==1].sum()
PNC_TopicsDF = pd.DataFrame([PNC_Topics['Trusts':'Market Environment']])
PNC_TopicsDF = PNC_TopicsDF.T
PNC_TopicsDF = PNC_TopicsDF.rename(columns = {0:'Topics'})
PNC_TopicsDF['Percentage'] = (PNC_TopicsDF['Topics']/PNC_TopicsDF['Topics'].sum()) 
PNC_TopicsDF

                      Topics  Percentage
Trusts                   0.0         0.0
Economic Environment     2.0         1.0
Wealth Management        0.0         0.0
Market Environment       0.0         0.0

In [91]:
PNC_Tonality = Master_Grid[Master_Grid['PNC Wealth Management']==1].sum()
PNC_TonalityDF = pd.DataFrame([PNC_Tonality['Positive':'Negative']])
PNC_TonalityDF = PNC_TonalityDF.T
PNC_TonalityDF = PNC_TonalityDF.rename(columns = {0:'Tonality'})
PNC_TonalityDF['Percentage'] = (PNC_TonalityDF['Tonality']/PNC_TonalityDF['Tonality'].sum()) 
PNC_TonalityDF

          Tonality  Percentage
Positive       2.0    0.333333
Neutral        4.0    0.666667
Negative       0.0    0.000000

In [92]:
PNC = Master_Grid[Master_Grid['PNC Wealth Management']==1]
content_list = []
for i in range(1,5):
    list1 = PNC[PNC[ContentQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
PNC_CQ = df.rename(columns = {0:'Content Quality'}, index = {0:'Single Mention',1:'Middle Mention', 2:'Thought Leadership', 3:'Feature'})
PNC_CQ['Percentage'] = (PNC_CQ['Content Quality']/PNC_CQ['Content Quality'].sum())
PNC_CQ

                    Content Quality  Percentage
Single Mention                    0    0.000000
Middle Mention                    0    0.000000
Thought Leadership                5    0.833333
Feature                           1    0.166667

In [93]:
PNC1 = Master_Grid[Master_Grid['Scored']==1]
PNC = PNC1[PNC1['PNC Wealth Management']==1]
content_list = []
for i in range(1,3):
    list1 = PNC[PNC[MediaQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
PNC_MQ = df.rename(columns = {0:'Media Quality'}, index = {0:'Tier1', 1:'Tier2'})
PNC_MQ['Percentage'] = (PNC_MQ['Media Quality']/PNC_MQ['Media Quality'].sum())
PNC_MQ

       Media Quality  Percentage
Tier1              2    0.666667
Tier2              1    0.333333

In [94]:
ST_Topics = Master_Grid[Master_Grid['SunTrust']==1].sum()
ST_TopicsDF = pd.DataFrame([ST_Topics['Trusts':'Market Environment']])
ST_TopicsDF = ST_TopicsDF.T
ST_TopicsDF = ST_TopicsDF.rename(columns = {0:'Topics'})
ST_TopicsDF['Percentage'] = (ST_TopicsDF['Topics']/ST_TopicsDF['Topics'].sum()) 
ST_TopicsDF

                      Topics  Percentage
Trusts                   0.0    0.000000
Economic Environment     1.0    0.083333
Wealth Management        6.0    0.500000
Market Environment       5.0    0.416667

In [95]:
ST_Tonality = Master_Grid[Master_Grid['SunTrust']==1].sum()
ST_TonalityDF = pd.DataFrame([ST_Tonality['Positive':'Negative']])
ST_TonalityDF = ST_TonalityDF.T
ST_TonalityDF = ST_TonalityDF.rename(columns = {0:'Tonality'})
ST_TonalityDF['Percentage'] = (ST_TonalityDF['Tonality']/ST_TonalityDF['Tonality'].sum()) 
ST_TonalityDF

          Tonality  Percentage
Positive       7.0     0.21875
Neutral       19.0     0.59375
Negative       6.0     0.18750

In [96]:
ST = Master_Grid[Master_Grid['SunTrust']==1]
content_list = []
for i in range(1,5):
    list1 = ST[ST[ContentQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
ST_CQ = df.rename(columns = {0:'Content Quality'}, index = {0:'Single Mention',1:'Middle Mention', 2:'Thought Leadership', 3:'Feature'})
ST_CQ['Percentage'] = (ST_CQ['Content Quality']/ST_CQ['Content Quality'].sum())
ST_CQ

                    Content Quality  Percentage
Single Mention                   12       0.375
Middle Mention                    0       0.000
Thought Leadership               12       0.375
Feature                           8       0.250

In [97]:
ST1 = Master_Grid[Master_Grid['Scored']==1]
ST = ST1[ST1['SunTrust']==1]
content_list = []
for i in range(1,3):
    list1 = ST[ST[MediaQuality]==i].shape[0]
    content_list.append(list1)
df = pd.DataFrame(content_list)
ST_MQ = df.rename(columns = {0:'Media Quality'}, index = {0:'Tier1', 1:'Tier2'})
ST_MQ['Percentage'] = (ST_MQ['Media Quality']/ST_MQ['Media Quality'].sum())
ST_MQ.iloc[:,1][1]

0.5161290322580645

In [98]:
writer = pd.ExcelWriter('WT_Tables_Q1.xlsx', engine = 'xlsxwriter')
#result.to_excel(writer, sheet_name = 'Share Of Voice') #PRvsEditorial
Competitor_SOV.to_excel(writer, sheet_name = 'Share Of Voice') #Overall SOV

#Key Themes SOV
Topics_SOV.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 10)
TrustsDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 20)
EcoenvDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 20, startcol = 9)
MrkEnvDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 40)
WealthMgmtDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 40, startcol = 9)
Com_Analysis.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 50) #Keythemes Competitive Analysis


#Tonality SOV
Tonality_SOV.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 62)
PositiveDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 70)
NeutralDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 70, startcol = 9)
NegativeDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 80)

#Content Quality SOV
Content_Quality.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 90)
SingleMentionDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 100)
MiddleMentionDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 100, startcol = 9)
ThoughtLeadershipDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 110)
FeatureDF.to_excel(writer, sheet_name = 'Share Of Voice', startrow = 110, startcol = 9)

#Competitors tables
#WT
WT_TopicsDF.to_excel(writer, sheet_name = 'Wilmington Trust')
WT_TonalityDF.to_excel(writer, sheet_name = 'Wilmington Trust', startrow = 20)
WT_CQ.to_excel(writer, sheet_name = 'Wilmington Trust', startrow = 27)
WT_MQ.to_excel(writer, sheet_name = 'Wilmington Trust', startrow = 36)

#BT
BT_TopicsDF.to_excel(writer, sheet_name = 'Bessemer Trust')
BT_TonalityDF.to_excel(writer, sheet_name = 'Bessemer Trust', startrow = 20)
BT_CQ.to_excel(writer, sheet_name = 'Bessemer Trust', startrow = 27)
BT_MQ.to_excel(writer, sheet_name = 'Bessemer Trust', startrow = 36)

#CS
NT_TopicsDF.to_excel(writer, sheet_name = 'Corporation Services')
NT_TonalityDF.to_excel(writer, sheet_name = 'Corporation Services', startrow = 20)
NT_CQ.to_excel(writer, sheet_name = 'Corporation Services', startrow = 27)
NT_MQ.to_excel(writer, sheet_name = 'Corporation Services', startrow = 36)

#PNC
PNC_TopicsDF.to_excel(writer, sheet_name = 'PNC Wealth Management')
PNC_TonalityDF.to_excel(writer, sheet_name = 'PNC Wealth Management', startrow = 20)
PNC_CQ.to_excel(writer, sheet_name = 'PNC Wealth Management', startrow = 27)
PNC_MQ.to_excel(writer, sheet_name = 'PNC Wealth Management', startrow = 36)

#ST
ST_TopicsDF.to_excel(writer, sheet_name = 'SunTrust')
ST_TonalityDF.to_excel(writer, sheet_name = 'SunTrust', startrow = 20)
ST_CQ.to_excel(writer, sheet_name = 'SunTrust', startrow = 27)
ST_MQ.to_excel(writer, sheet_name = 'SunTrust', startrow = 36)


writer.save()

In [122]:
from pptx import Presentation
from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE
from pptx.util import Inches
from pptx.dml.color import RGBColor
from pptx.enum.chart import XL_LABEL_POSITION
from pptx.enum.chart import XL_LEGEND_POSITION
from pptx.enum.chart import XL_TICK_MARK
from pptx.util import Pt
from pptx.util import Inches

path = 'WilmingtonTrust.pptx'
prs = Presentation(path)
#slide layouts

#title slide
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)

subtitle  = slide.placeholders[0]
left = Inches(3)
top = Inches(3)
width = Inches(5)
height = Inches(1)

pic = slide.shapes.add_picture("WT.jpg", left,top, width, height)
subtitle.text = "Media Measurement Report Q2 2017"

#summary slide

summary_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(summary_slide_layout)

title = slide.shapes.title
title.text = "Q2 Summary"

#Look ahead slide

Look_ahead = prs.slide_layouts[0]
slide = prs.slides.add_slide(Look_ahead)

title = slide.shapes.title
title.text = "Q2 Look Ahead"

#Media Dashboard slide

Media_dashboard =prs.slide_layouts[0]
slide_dashboard = prs.slides.add_slide(Media_dashboard)

title = slide_dashboard.shapes.title
title.text = "Media Dashboard"
#title.font.size = Pt(20)

#Traditional media start slide

Media =prs.slide_layouts[0]
slide = prs.slides.add_slide(Media)

title = slide.shapes.title
title.text = "Traditional Media"
subtitle.text = "Q1 2017"

#Share of Voice slide

SOV=prs.slide_layouts[0]
slide_SOV = prs.slides.add_slide(SOV)
title = slide.shapes.title
#title.text = "Share of Voice"
#title.font.size = Pt(15)

#Mentions over time slide

Mentions_over_time = prs.slide_layouts[0]
slide_MOT = prs.slides.add_slide(Mentions_over_time)

#Content Quality slide

CQ_slide_layout = prs.slide_layouts[0]
slide_CQ = prs.slides.add_slide(CQ_slide_layout)

#Content Quality BD slide

CQ_slide_layout1= prs.slide_layouts[0]
slide_CQ1 = prs.slides.add_slide(CQ_slide_layout1)

#tonality slide
T_slide_layout = prs.slide_layouts[0]
slide_T = prs.slides.add_slide(T_slide_layout)


#Topics slide
Top_slide_layout = prs.slide_layouts[0]
slide_Top = prs.slides.add_slide(Top_slide_layout)

#Media Quality
MQ_slide_layout = prs.slide_layouts[0]
slide_MQ = prs.slides.add_slide(MQ_slide_layout)


#define chart data
#Share of voice slide
chart_data_SOV = ChartData()
chart_data_SOV.categories = ['Northern Trust', 'Bessemer Trust', 'SunTrust', 'Wilmington Trust', 'PNC Wealth Management']
chart_data_SOV.add_series('SOV', (Competitor_SOV.iloc[:,1][0], Competitor_SOV.iloc[:,1][1],
                                  Competitor_SOV.iloc[:,1][2],
                                  Competitor_SOV.iloc[:,1][3],
                                  Competitor_SOV.iloc[:,1][4]))
x, y, cx, cy = Inches(5), Inches(2), Inches(4.5), Inches(4.5)
chart = slide_SOV.shapes.add_chart(XL_CHART_TYPE.PIE, x, y, cx, cy, chart_data_SOV).chart
chart.plots[0].has_data_labels = True
data_labels = chart.plots[0].data_labels
data_labels.number_format = '0%'
data_labels.position = XL_LABEL_POSITION.INSIDE_END
data_labels.font.size = Pt(12)
data_labels.font.bold = True
title = slide_SOV.shapes.title
title.text = "Share of Voice"


#Media Quality 
title = slide_MQ.shapes.title
title.text = "Competitive Analysis - Media Quality"

chart_data_MQ = ChartData()
chart_data_MQ.categories = ['Wilmington Trust', 'Bessemer trust', 'Northern Trust', 'PNC Wealth Management', 'SunTrust']
chart_data_MQ.add_series('Tier', (MQ.iloc[:,0][0], MQ.iloc[:,0][1], MQ.iloc[:,0][2], MQ.iloc[:,0][3], MQ.iloc[:,0][4]))
chart_data_MQ.add_series('Tier', (MQ.iloc[:,1][0], MQ.iloc[:,1][1], MQ.iloc[:,1][2], MQ.iloc[:,1][3], MQ.iloc[:,1][4]))
x, y, cx, cy = Inches(1), Inches(1), Inches(8), Inches(3)
chart = slide_MQ.shapes.add_chart(XL_CHART_TYPE.BAR_CLUSTERED, x, y, cx, cy, chart_data_MQ).chart
##formatting
#labels
plot = chart.plots[0]
plot.has_data_labels = True
data_labels = plot.data_labels
data_labels.font.size = Pt(10)
data_labels.position = XL_LABEL_POSITION.INSIDE_END
#graph
category_axis = chart.category_axis
category_axis.has_major_gridlines = False
category_axis.has_tick_mark = XL_TICK_MARK.OUTSIDE
category_axis.tick_labels.font.size = Pt(8) 

value_axis = chart.value_axis
value_axis.minor_tick_mark = XL_TICK_MARK.OUTSIDE
value_axis.has_major_gridlines = False
tick_labels = value_axis.tick_labels
tick_labels.font.bold = False
tick_labels.font.size = Pt(12)

#Tonality
title = slide_T.shapes.title
title.text = "Competitive Analysis - Tonality"

chart_data_T = ChartData()
chart_data_T.categories = ['Positive', 'Neutral', 'Negative']
chart_data_T.add_series('Wilmingtion Trust', (WT_TonalityDF.iloc[:,1][0], WT_TonalityDF.iloc[:,1][1], WT_TonalityDF.iloc[:,1][2]))
x, y, cx, cy = Inches(3.5), Inches(1), Inches(3.5), Inches(3.5)
chart = slide_T.shapes.add_chart(XL_CHART_TYPE.DOUGHNUT, x, y, cx, cy, chart_data_T).chart
chart.has_legend = True
chart.legend.font.size = Pt(14)
chart.legend.position = XL_LEGEND_POSITION.BOTTOM
title = slide_T.shapes.title

chart_data_T = ChartData()
chart_data_T.categories = ['Positive', 'Neutral', 'Negative']
chart_data_T.add_series('PNC', (PNC_TonalityDF.iloc[:,1][0], PNC_TonalityDF.iloc[:,1][1], PNC_TonalityDF.iloc[:,1][2]))
x, y, cx, cy = Inches(1), Inches(1), Inches(2.25), Inches(2.25)
chart = slide_T.shapes.add_chart(XL_CHART_TYPE.DOUGHNUT, x, y, cx, cy, chart_data_T).chart
chart.has_legend = False

chart_data_T = ChartData()
chart_data_T.categories = ['Positive', 'Neutral', 'Negative']
chart_data_T.add_series('SunTrust', (ST_TonalityDF.iloc[:,1][0], ST_TonalityDF.iloc[:,1][1], ST_TonalityDF.iloc[:,1][2]))
x, y, cx, cy = Inches(7), Inches(1), Inches(2.25), Inches(2.25)
chart = slide_T.shapes.add_chart(XL_CHART_TYPE.DOUGHNUT, x, y, cx, cy, chart_data_T).chart
chart.has_legend = False


chart_data_T = ChartData()
chart_data_T.categories = ['Positive', 'Neutral', 'Negative']
chart_data_T.add_series('Bessemer Trust', (BT_TonalityDF.iloc[:,1][0], BT_TonalityDF.iloc[:,1][1], BT_TonalityDF.iloc[:,1][2]))
x, y, cx, cy = Inches(1), Inches(4), Inches(2.25), Inches(2.25)
chart = slide_T.shapes.add_chart(XL_CHART_TYPE.DOUGHNUT, x, y, cx, cy, chart_data_T).chart
chart.has_legend = False


chart_data_T = ChartData()
chart_data_T.categories = ['Positive', 'Neutral', 'Negative']
chart_data_T.add_series('Northern Trust', (NT_TonalityDF.iloc[:,1][0], NT_TonalityDF.iloc[:,1][1], NT_TonalityDF.iloc[:,1][2]))
x, y, cx, cy = Inches(7), Inches(4), Inches(2.25), Inches(2.25)
chart = slide_T.shapes.add_chart(XL_CHART_TYPE.DOUGHNUT, x, y, cx, cy, chart_data_T).chart
chart.has_legend = False


#Topics
title = slide_Top.shapes.title
title.text = "Topics"

chart_data_Top = ChartData()
chart_data_Top.categories = ['Trusts', 'Economic Environment', 'Wealth Management', 'Market Environment']
chart_data_Top.add_series('Wilmington Trust', (Com_Analysis.iloc[:,0][0], Com_Analysis.iloc[:,1][0], Com_Analysis.iloc[:,2][0], Com_Analysis.iloc[:,3][0]))
chart_data_Top.add_series('Bessemer Trust', (Com_Analysis.iloc[:,0][1], Com_Analysis.iloc[:,1][1], Com_Analysis.iloc[:,2][1], Com_Analysis.iloc[:,3][1]))
chart_data_Top.add_series('Northern Trust', (Com_Analysis.iloc[:,0][2], Com_Analysis.iloc[:,1][2], Com_Analysis.iloc[:,2][2], Com_Analysis.iloc[:,3][2]))
chart_data_Top.add_series('PNC Wealth Management', (Com_Analysis.iloc[:,0][3], Com_Analysis.iloc[:,1][3], Com_Analysis.iloc[:,2][3], Com_Analysis.iloc[:,3][3]))
chart_data_Top.add_series('SunTrust', (Com_Analysis.iloc[:,0][4], Com_Analysis.iloc[:,1][4], Com_Analysis.iloc[:,2][4], Com_Analysis.iloc[:,3][4]))
x, y, cx, cy = Inches(1), Inches(1), Inches(8), Inches(3)
chart = slide_Top.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data_Top).chart
##formatting
#labels
plot = chart.plots[0]
plot.has_data_labels = True
data_labels = plot.data_labels
data_labels.font.size = Pt(10)
data_labels.position = XL_LABEL_POSITION.INSIDE_END
#graph
category_axis = chart.category_axis
category_axis.has_major_gridlines = False
category_axis.has_tick_mark = XL_TICK_MARK.OUTSIDE
category_axis.tick_labels.font.size = Pt(8) 

value_axis = chart.value_axis
value_axis.minor_tick_mark = XL_TICK_MARK.OUTSIDE
value_axis.has_major_gridlines = False
tick_labels = value_axis.tick_labels
tick_labels.font.bold = False
tick_labels.font.size = Pt(12)

#Content Quality
title = slide_CQ.shapes.title
title.text = "Wilmington Trust - Content Quality"
#title.font.size = Pt(14)

chart_data_CQ = ChartData()
chart_data_CQ.categories = ['Single Mention', 'Middle Mention', 'Thought Leadership', 'Feature']
chart_data_CQ.add_series('Content Quality', (CQ1.iloc[:,1][0], CQ1.iloc[:,1][1], CQ1.iloc[:,1][2], CQ1.iloc[:,1][3]))
x, y, cx, cy = Inches(5), Inches(3), Inches(6), Inches(3)
chart = slide_CQ.shapes.add_chart(XL_CHART_TYPE.PIE, x, y, cx, cy, chart_data_CQ).chart
chart.plots[0].has_data_labels = True
data_labels = chart.plots[0].data_labels
data_labels.number_format = '0%'
data_labels.position = XL_LABEL_POSITION.INSIDE_END

#Single Mention
title = slide_CQ1.shapes.title
title.text = "Competitive Analysis - Content Quality"

chart_data_SM = ChartData()
chart_data_SM.categories = ['Wilmington Trust', 'Bessemer Trust', 'Northern Trust', 'PNC Wealth Management', 'SunTrust']
chart_data_SM.add_series('Single Mention', (CQ.iloc[:,0][0], CQ.iloc[:,0][1], CQ.iloc[:,0][2], CQ.iloc[:,0][3], CQ.iloc[:,0][4]))
x, y, cx, cy = Inches(0), Inches(1), Inches(4), Inches(3)
chart = slide_CQ1.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data_SM).chart
plot = chart.plots[0]
plot.has_data_labels = True
data_labels = plot.data_labels
data_labels.font.size = Pt(10)
data_labels.position = XL_LABEL_POSITION.INSIDE_END
#graph
category_axis = chart.category_axis
category_axis.has_major_gridlines = False
category_axis.has_tick_mark = XL_TICK_MARK.OUTSIDE
category_axis.tick_labels.font.size = Pt(8) 

value_axis = chart.value_axis
value_axis.minor_tick_mark = XL_TICK_MARK.OUTSIDE
value_axis.has_major_gridlines = False
tick_labels = value_axis.tick_labels
tick_labels.font.bold = False
tick_labels.font.size = Pt(8)

#Middle Mention

chart_data_MM = ChartData()
chart_data_MM.categories = ['Wilmington Trust', 'Bessemer Trust', 'Northern Trust', 'PNC Wealth Management', 'SunTrust']
chart_data_MM.add_series('Middle Mention', (CQ.iloc[:,1][0], CQ.iloc[:,1][1], CQ.iloc[:,1][2], CQ.iloc[:,1][3], CQ.iloc[:,1][4]))
x, y, cx, cy = Inches(5), Inches(1), Inches(4), Inches(3)
chart = slide_CQ1.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data_MM).chart
plot = chart.plots[0]
plot.has_data_labels = True
data_labels = plot.data_labels
data_labels.font.size = Pt(10)
data_labels.position = XL_LABEL_POSITION.INSIDE_END
#graph
category_axis = chart.category_axis
category_axis.has_major_gridlines = False
category_axis.has_tick_mark = XL_TICK_MARK.OUTSIDE
category_axis.tick_labels.font.size = Pt(8) 

value_axis = chart.value_axis
value_axis.minor_tick_mark = XL_TICK_MARK.OUTSIDE
value_axis.has_major_gridlines = False
tick_labels = value_axis.tick_labels
tick_labels.font.bold = False
tick_labels.font.size = Pt(8)

#Thought Leadership

chart_data_TL = ChartData()
chart_data_TL.categories = ['Wilmington Trust', 'Bessemer Trust', 'Northern Trust', 'PNC Wealth Management', 'SunTrust']
chart_data_TL.add_series('Thought Leadership', (CQ.iloc[:,2][0], CQ.iloc[:,2][1], CQ.iloc[:,2][2], CQ.iloc[:,2][3], CQ.iloc[:,2][4]))
x, y, cx, cy = Inches(0), Inches(4), Inches(4), Inches(3)
chart = slide_CQ1.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data_TL).chart
plot = chart.plots[0]
plot.has_data_labels = True
data_labels = plot.data_labels
data_labels.font.size = Pt(10)
data_labels.position = XL_LABEL_POSITION.INSIDE_END
#graph
category_axis = chart.category_axis
category_axis.has_major_gridlines = False
category_axis.has_tick_mark = XL_TICK_MARK.OUTSIDE
category_axis.tick_labels.font.size = Pt(8) 

value_axis = chart.value_axis
value_axis.minor_tick_mark = XL_TICK_MARK.OUTSIDE
value_axis.has_major_gridlines = False
tick_labels = value_axis.tick_labels
tick_labels.font.bold = False
tick_labels.font.size = Pt(8)

#Feature

chart_data_F = ChartData()
chart_data_F.categories = ['Wilmington Trust', 'Bessemer Trust', 'Northern Trust', 'PNC Wealth Management', 'SunTrust']
chart_data_F.add_series('Feature', (CQ.iloc[:,3][0], CQ.iloc[:,3][1], CQ.iloc[:,3][2], CQ.iloc[:,3][3], CQ.iloc[:,3][4]))
x, y, cx, cy = Inches(5), Inches(4), Inches(4), Inches(3)
chart = slide_CQ1.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data_F).chart
plot = chart.plots[0]
plot.has_data_labels = True
data_labels = plot.data_labels
data_labels.font.size = Pt(10)
data_labels.position = XL_LABEL_POSITION.INSIDE_END
#graph
category_axis = chart.category_axis
category_axis.has_major_gridlines = False
category_axis.has_minor_gridlines = False
category_axis.has_tick_mark = XL_TICK_MARK.OUTSIDE
category_axis.tick_labels.font.size = Pt(8) 

value_axis = chart.value_axis
value_axis.minor_tick_mark = XL_TICK_MARK.OUTSIDE
value_axis.has_major_gridlines = False
tick_labels = value_axis.tick_labels
tick_labels.font.bold = False
tick_labels.font.size = Pt(8)

chart.plots[0].has_data_labels = True
data_labels = chart.plots[0].data_labels
#data_labels.number_format = '0%'
prs.save('WT_charts.pptx')